version: '3'

services: 
  database: 
    image: 'mysql_vreg:8.0.22'
    restart: always
    container_name: vreg_db
    environment: 
      - MYSQL_ROOT_PASSWORD=admin
      - MYSQL_DATABASE=vreg
      - MYSQL_USER=vreg
      - MYSQL_PASSWORD=vregpass
    ports:
      - '3306:3306'
  vreg:
    image: 'vreg:1.0'
    restart: on-failure
    depends_on:
      - database
    ports: 
      - '80:80'
    environment:
      - MYSQL_DB_HOST=database
      - MYSQL_DB_PORT=3306
      - MYSQL_DB_USERNAME=vreg 
      - MYSQL_DB_PASSWORD=vregpass
      - PORT=80

