version: '3'

services: 
  database: 
    build:
      context: .
      dockerfile: Dockerfile_mysql
    image: 'mysql_vreg:8.0.22'
    restart: always
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci --init-connect='SET NAMES UTF8;' --innodb-flush-log-at-trx-commit=0
    container_name: vreg_db
    environment: 
      - MYSQL_ROOT_PASSWORD=admin
      - MYSQL_DATABASE=vreg
      - MYSQL_USER=vreg
      - MYSQL_PASSWORD=vregpass
    ports:
      - '3306:3306'
  vreg:
    build:
      context: .
      dockerfile: Dockerfile_vreg
    image: 'vreg:1.0'
    restart: on-failure
    container_name: vreg
    depends_on:
      - database
    ports: 
      - '80:80'
    environment:
      - MYSQL_DB_HOST=database
      - MYSQL_DB_PORT=3306
      - MYSQL_DB_USERNAME=vreg 
      - MYSQL_DB_PASSWORD=vregpass
      - PORT=80

